# Generated by Django 3.0.5 on 2020-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
