# Generated by Django 3.0.5 on 2020-05-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200517_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adDress',
            new_name='address',
        ),
    ]
