# Generated by Django 3.0.5 on 2020-05-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200517_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='lon',
            new_name='longitude',
        ),
    ]
